# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Call C function from Rcpp
#' @export
futhark_entry_main_cpp <- function(l, a, b, c) {
    .Call('_ggpointgrid_futhark_entry_main_cpp', PACKAGE = 'ggpointgrid', l, a, b, c)
}

