# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

futhark_entry_arrange_from_coordinates_cpp <- function(grid_xs, grid_ys, pts_x, pts_y) {
    .Call('_ggpointgrid_futhark_entry_arrange_from_coordinates_cpp', PACKAGE = 'ggpointgrid', grid_xs, grid_ys, pts_x, pts_y)
}

